name: Renovate
on:
  workflow_call:
    inputs:
      token:
        description: "Authentication token"
        required: true
        type: string
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.1
        env:
          # Repository taken from variable to keep configuration file generic
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Onboarding not needed for self hosted
          RENOVATE_ONBOARDING: "false"
          # Git commit author used, must match GitHub App
          RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
        with:
          configurationFile: ".github/renovate.json"
          token: ${{ inputs.token }}
